version: '3.8'

services:
  api:
    image: ${DOCKER_REGISTRY-}saveplanapi
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    volumes: 
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      # - /etc/ssl:/home/app/.aspnet/ssl:ro  
      - C:\ProgramData\SSL:/home/app/.aspnet/ssl:ro
    depends_on: 
      - "database"
    ports:
      - "8080:8080"
      - "7000:7000"
    #deploy: 
      #mode: replicated
      #replicas: 2
      #endpoint_mode: vip

  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}    
    volumes:
      - ./.containers/save-plan:/var/lib/postgresql/data
    ports:
        - 5432:5432 

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_DB=postgres
      - KC_DB_USERNAME=${DB_USER}
      - KC_DB_PASSWORD=${DB_PASSWORD}
      - KC_DB_SCHEMA=users
      - KC_DB_URL_HOST=database
      - KC_DB_URL_DATABASE=${DB_NAME}
      - KC_HOSTNAME=localhost
      - KEYCLOAK_ADMIN=${KC_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
    depends_on:
      - database  
    volumes: 
      - ./.containers/identity:/opt/keycloack/data
    ports:
      - 18080:8080
 
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment: 
      - ACCEPT_EULA=Y
    volumes:
      - ./seq-data:/dat   
    ports:
      - 5341:5341
      - 8081:80 
  
  web-server:
    image: nginx:latest
    container_name: web-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      #- /etc/ssl:/etc/nginx/ssl:ro  
      - C:\ProgramData\SSL:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

      
